version: '3.8'

services:
  # --- BASE DE DATOS AUTORES (MYSQL) ---
  authors-db:
    image: mysql:8.0
    container_name: authors-db
    restart: always
    environment:
      MYSQL_DATABASE: db_authors
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"

  # --- MICROSERVICIO AUTORES (PYTHON) ---
  authors-service:
    build: ./authors-service
    container_name: authors-service
    ports:
      - "8000:8000"
    depends_on:
      - authors-db
    environment:
      DATABASE_URL: mysql+pymysql://root:root_password@authors-db/db_authors

  # --- BASE DE DATOS PUBLICACIONES (POSTGRES) ---
  publications-db:
    image: postgres:15
    container_name: publications-db
    restart: always
    environment:
      POSTGRES_DB: db_publications
      POSTGRES_USER: admin_pubs
      POSTGRES_PASSWORD: PubsPass43*
    ports:
      - "5432:5432"

  # --- MICROSERVICIO PUBLICACIONES (LARAVEL) ---
  publications-service:
    build: ./publications-service
    container_name: publications-service
    ports:
      - "8001:8001"
    depends_on:
      - publications-db
      - authors-service
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: publications-db
      DB_PORT: 5432
      DB_DATABASE: db_publications
      DB_USERNAME: admin_pubs
      DB_PASSWORD: PubsPass43*
      # Comunicación interna: Nombre del servicio + puerto interno
      AUTHORS_SERVICE_URL: http://authors-service:8000

  # --- FRONTEND (REACT) ---
  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "3000:3000"
    depends_on:
      - publications-service
      - authors-service
    environment:
      # El navegador accede vía localhost porque los puertos están mapeados al host
      REACT_APP_API_BOOKS: http://localhost:8001/api
      REACT_APP_API_AUTHORS: http://localhost:8000